#Create Pipeline with name
name: Rajkumar App containerization Pipeline
#Trigger section -- When this pipelin should start 
on:
  push:
    branches:
    - "dev"

#creating multiple jobs
jobs:
  rajk-sast-job:
    runs-on: ubuntu-latest
    steps:
#      - name: just checking version
#        run: |
#          echo pwd
#          sonar-scanner.bat -D"sonar.projectKey=rajk-python-project" -D"sonar.sources=." -D"sonar.host.url=http://44.219.46.64:9000" -D"sonar.token=sqp_4cfb7f50e0b877ae84c8aa7324e277c8b5e238a4"#

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rajk-artifact
          path: |
            .
            !**/.git*
            !**/*.md*

  rajk-build-job:
    runs-on: ubuntu-latest
    needs: rajk-sast-job
    steps:
      - name: just checking version
        run: |
          echo "docker related details."
          docker version
          docker-compose version

      - name: downloading artifact
        uses: actions/download-artifact@v4
        with:
          name: rajk-artifact
          path: .

      - name: docker compose to build and test
        run: |
          ls -a
          docker-compose up -d --build
          sleep 2
          docker-compose ps

      - name: verify health sonar
        run: |
          echo "access health"
          curl -f http://localhost.1234/health.html

