#Create Pipeline with name
name: Rajkumar App containerization Pipeline
#Trigger section -- When this pipelin should start 
on:
  push:
    branches:
    - "dev"

#jobs - what jobs need to perform

jobs:
  rajkumar-image-build:
    runs-on: ubuntu-latest
    #This server will be provison by github backend for this job
    steps:
    - name: run some basic commands on above server to do some verification
      run: "uname -r \nwhoami\ncat /etc/os-release\ndocker version\ndocker-compose version\n"
    - name: using pre-defined github workflow to get copy github repo code to runners
      uses: actions/checkout@v4

    - name: Offical Sonarqube scan update
      uses: SonarSource/sonarqube-scan-action@v2.1.0
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=rajk-python-project 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: verify github code
      run: "ls -a\ndocker-compose up -d \nsleep 2\ndocker-compose ps\n"
    - name: upload docker site
      # - name: verify health applicaiton
      #   run: "echo \"Accessing the page using curl \ncurl  http://localhost:1234/health.html || exit 1\n#magic___^_^___line\n"
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: rebuild image in docker hub and push it doccker hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rajkumar-webui:version2

    - name: Docker logout from runners
      run: docker logout
