#Create Pipeline with name
name: Rajkumar App containerization Pipeline
#Trigger section -- When this pipelin should start 
on:
  push:
    branches:
    - "main"

#jobs - what jobs need to perform

jobs:
  rajkumar-image-build:
    runs-on: ubuntu-latest
    #This server will be provison by github backend for this job
    steps:
    - name: run some basic commands on above server to do some verification
      run: "uname -r \nwhoami\ncat /etc/os-release\ndocker version\ndocker-compose version\n"
    - name: using pre-defined github workflow to get copy github repo code to runners
      uses: actions/checkout@v4
    - name: verify github code
      run: |
        ls -a
        docker-compose up -d 
        sleep 2
        docker-compose ps
      

